"""add user, time_log, task, tag, shedule, notification files

Revision ID: fb88c9878305
Revises: 55ac2b0873a0
Create Date: 2026-03-22 16:18:10.567344

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb88c9878305'
down_revision: Union[str, Sequence[str], None] = '55ac2b0873a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
